keystore_path = File.expand_path("../../keystore.jks", __FILE__)
json_key_file = File.expand_path("../../api-codes.json", __FILE__)

lane :build_apk do
	gradle(
		task: 'assemble',
		build_type: 'Release',
		project_dir: 'pure-android/',
		properties: {
			"android.injected.signing.store.file" => keystore_path,
			"android.injected.signing.store.password" => "123456",
			"android.injected.signing.key.alias" => "mykey",
			"android.injected.signing.key.password" => "123456",
		}
	)
end

lane :build_aab do
	gradle(
		task: 'bundle',
		build_type: 'Release',
		project_dir: 'pure-android/',
		properties: {
			"android.injected.signing.store.file" => keystore_path,
			"android.injected.signing.store.password" => "123456",
			"android.injected.signing.key.alias" => "mykey",
			"android.injected.signing.key.password" => "123456",
		}
	)
end

lane :publish
	supply(
		json_key: File.expand_path("../../api-codes.json", __FILE__),
		package_name: "works.buddy.allaroundapp",
		apk: "./build/outputs/apk/release/app-release.apk",
		track: "internal"
	)
end
